apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
 {{- if  .Values.service.type }}
  type: {{ .Values.service.type }}
 {{- end }}
  selector:
    app: {{ .Release.Name }}   
{{ range .Values.service.ports }}
  ports:
    - protocol: {{ .protocol | default "TCP" }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
#      {{- if .nodePort  }}
#      nodePort: {{ .nodePort }}
#     {{- end }}
{{ end }}
