apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
    {{- if  .Values.service.type }}
    type: {{ .Values.service.type }}
    {{- end }}
{{ range .Values.service.ports }}
  ports:
    - protocol: {{ .protocol | default "TCP" }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if .nodePort  }}
      nodePort: {{ .nodePort }}
      {{- end }}
{{ end }}
